### ISSUE TITLE
how to change proxy setting

### ISSUE THREAD

**Issue by HarryChen55** [Ecks1337/RyuSAK#29]
hi everyone,

I changed the proxy setting to a wrong address, now I can't even load the app.

How can I change the proxy setting back?

Thanks!!

**Comment by HarryChen55** [comment]
Error occurred in handler for 'load-components': FetchError: request to https://api.github.com/repos/Ecks1337/RyuSAK/releases/latest failed, reason: connect EHOSTUNREACH 0.0.4.65:80 - Local (10.20.30.11:51349)
    at ClientRequest.<anonymous> (/Users/harry/Documents/switch/RyuSAK/.webpack/main/index.js:26973:11)
    at ClientRequest.emit (node:events:390:28)
    at onerror (/Users/harry/Documents/switch/RyuSAK/.webpack/main/index.js:3011:21)
    at callbackError (/Users/harry/Documents/switch/RyuSAK/.webpack/main/index.js:3030:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  type: 'system',
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH',
  erroredSysCall: 'connect'
}

**Comment by Ecks1337** [comment]
Simply delete or edit the proxy file. The file is located in `%appdata%\RyuSAK\proxy` on Windows
