### ISSUE TITLE
Stuck on “Loading Data" screen MacOS 13.5

### ISSUE THREAD

**Issue by JustJagd** [Ecks1337/RyuSAK#88]
I installed RyuSAK with the .dmg file (1.6.1). First I had the "RyuSAK is damaged and cannot opened" Problem. I got that fixed with this command "xattr -cr /Applications/RyuSAK.app/" that i found on this github. RyuSAK finally started, after i agreed to the the ToS the application says "Loading Data". The circle in the middle is moving, so it's not frozen, but it does not progress

Edit: It looks like the developer stopped working on ryusak, thats why it may be not working anymore
<img width="1159" alt="Bildschirmfoto 2023-10-23 um 14 06 56" src="https://github.com/Ecks1337/RyuSAK/assets/148771997/e3c3462a-2222-4fdc-b885-bdec57697930">

**Comment by Pratham1875** [comment]
Same here and its really frustrating and i need it for fixing stuttering
![Uploading Screenshot 2023-10-23 at 6.41.06 PM.png…]()
ing

**Comment by JustJagd** [comment]
it seems like the developor stopped working on ryusak and stopped the servers :( https://github.com/Ecks1337/RyuSAK/issues/87#issuecomment-1774738104

**Comment by FennyFatal** [comment]
#86 at least makes the thing work without those resources.

**Comment by Kr0sFyr3** [comment]
```Uncaught (in promise) Error: Error invoking remote method 'load-components': Error: Not Found
    at EventEmitter.o.invoke (node:electron/js2c/renderer_init:57:526)```  Found following error in dev mode.

**Comment by gardotd426** [comment]
Same exact issue on Linux.

Terminal:

```
Error occurred in handler for 'load-components': Error
    at t.<anonymous> (/usr/lib/ryusak/resources/app/.webpack/main/index.js:2:411271)
    at /usr/lib/ryusak/resources/app/.webpack/main/index.js:2:408448
    at Object.next (/usr/lib/ryusak/resources/app/.webpack/main/index.js:2:408553)
    at a (/usr/lib/ryusak/resources/app/.webpack/main/index.js:2:407290)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by AlexQSWitch** [comment]
Same issue on mac sonoma 14, RyuSAK v1.6.2, v1.6.1, v1.6.0 and v1.5.0

**Comment by hajosattila** [comment]
Same here on Arch

**Comment by beastlybeast** [comment]
Is anyone NOT getting this issue?
